
# Site settings
title: Intelligent Vision and Robotics Laboratory
name: Intelligent Vision and Robotics Laboratory
subtitle: Laboratory Introduction
email: ntdxzjxy@163.com
description: >
  Financial Economist
baseurl: ""
url: "https://zhangjianlab.github.io/"
github_username:  ZhangJianLab
disqus_baseurl: "https://zhangjianlab.github.io/"
disqus_shortname: https-zhangjianlab-github-io/
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Paul E. Soto"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: ZhangJianLab
    url: "https://zhangjianlab.github.io/"
    desc: Fork me on GitHub
    share: false

